version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - api-network

  api-template-nestjs:
    build:
      context: .
    container_name: api-template-nestjs
    ports:
      - 3000:3000
    depends_on:
      - mysql
    networks:
      - api-network

networks:
  api-network:
    name: api-network
    external: true
    driver: bridge

volumes:
  db:
