version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  api-template-nestjs:
    build:
      context: .
    container_name: api-template-nestjs
    ports:
      - 3000:3000
    depends_on:
      - mysql
